# Generated by Django 5.2.8 on 2025-11-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleSKU', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('reorderMax', models.IntegerField(default=0)),
                ('averageCost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('chantierRef', models.CharField(max_length=255)),
                ('urgency', models.CharField(max_length=50)),
                ('budget', models.FloatField()),
                ('requester', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('reliabilityIndex', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('poNumber', models.AutoField(primary_key=True, serialize=False)),
                ('totalCost', models.FloatField()),
                ('status', models.CharField(default='Pending Approval', max_length=50)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achat.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achat.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('poReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achat.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('grnID', models.AutoField(primary_key=True, serialize=False)),
                ('receivedQuantity', models.IntegerField()),
                ('dateReceived', models.DateField()),
                ('poReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achat.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotationID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('deliveryTime', models.DateField()),
                ('validity', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achat.supplier')),
            ],
        ),
    ]
