# Generated by Django 5.2.8 on 2025-11-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseID', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
