# Generated by Django 5.2.8 on 2025-11-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_2fa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_2fa_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
